org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=1 -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
android.usesSdkInManifest.disallowed=true
android.packageNamesViolationCheck=true